name: Publish to Docker Hub

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName

      - uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            smoothdenis/deploy-code-server
          tags: |
            type=pep440,pattern={{version}}-devpack
            latest-devpack

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=smoothdenis/deploy-code-server:buildcache-devpack
          cache-to: type=registry,ref=smoothdenis/deploy-code-server:buildcache-devpack,mode=max
        env: 
          IMAGE_TAG: ${{ steps.tagName.outputs.tag }}
